### ISSUE TITLE
Building vspec2protobuf, not finding files and directory

### ISSUE THREAD

**Issue by majorkhan** [COVESA/vss-tools#214]
Hi,

I am using  

**py  vspec2protobuf.py -u ../tests/vspec/test_datatypes/test.vspec -I ../../../../spec ../../../../spec/VehicleSignalSpecification.vspec  Ehsan.proto**

to convert but it is showing

**Reading unit definitions from ../tests/vspec/test_datatypes/test.vspec
Traceback (most recent call last):
  File "C:\Users\major\Documents\Research work\Covesa\new-vss\vss-tools-master\vss-tools-master\contrib\vspec2protobuf.py", line 85, in <module>
    tree = vspec.load_tree(args.vspec_file, include_dirs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\major\AppData\Local\Programs\Python\Python311\Lib\site-packages\vss_tools-1.0-py3.11.egg\vspec\__init__.py", line 93, in load_tree
    tree = render_tree(dict_tree, merge_private, break_on_unknown_attribute=break_on_unknown_attribute,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\major\AppData\Local\Programs\Python\Python311\Lib\site-packages\vss_tools-1.0-py3.11.egg\vspec\__init__.py", line 624, in render_tree
    render_subtree(child_nodes, tree_root, break_on_unknown_attribute=break_on_unknown_attribute,
  File "C:\Users\major\AppData\Local\Programs\Python\Python311\Lib\site-packages\vss_tools-1.0-py3.11.egg\vspec\__init__.py", line 647, in render_subtree
    render_subtree(child_nodes, new_element, break_on_unknown_attribute,
  File "C:\Users\major\AppData\Local\Programs\Python\Python311\Lib\site-packages\vss_tools-1.0-py3.11.egg\vspec\__init__.py", line 639, in render_subtree
    new_element = VSSNode(element_name, current_element, parent=parent, break_on_unknown_attribute=break_on_unknown_attribute,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\major\AppData\Local\Programs\Python\Python311\Lib\site-packages\vss_tools-1.0-py3.11.egg\vspec\model\vsstree.py", line 108, in __init__
    self.unpack_source_dict()
  File "C:\Users\major\AppData\Local\Programs\Python\Python311\Lib\site-packages\vss_tools-1.0-py3.11.egg\vspec\model\vsstree.py", line 146, in unpack_source_dict
    self.unit = Unit.from_str(self.source_dict["unit"])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\major\AppData\Local\Programs\Python\Python311\Lib\site-packages\vss_tools-1.0-py3.11.egg\vspec\model\constants.py", line 98, in 
from_str
    return cls.__reverse_lookup__[value]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'V'**

I appreciate your help.

**Comment by SebastianSchildt** [comment]
Not very familiar with it, and since it is in contrib, it may not support everything. Maybe you have an older version of the tools installed?  I was able to get it to run in my working directory with the standard catalogue like this

```
python vspec2protobuf.py -I ../spec/ -u ../../spec/units.yaml ../../spec/VehicleSignalSpecification.vspec      outtest.proto
```

(My setup had https://github.com/COVESA/vehicle_signal_specification/ checked out at master with vss-tools submodule, which I then also manually checked out to current master)

Doesn't  really explain your problem, but maybe it works for you as well, and gives you a better starting point

**Comment by erikbosch** [comment]
I guess it complains that it cannot find Volts (V).

You are using the new feature to specify units (`-u ../tests/vspec/test_datatypes/test.vspec`) but you give a test file as input which does not contain any unit definitions at all. Either skip the `-u` parameter (to use default unit file, still supported), or make sure you include the file in https://github.com/COVESA/vehicle_signal_specification/blob/master/spec/units.yaml.

We should better improve the handling if units cannot be found, I created #215 for this

**Comment by majorkhan** [comment]
Thank you
